import{a as b,i as l,S as L}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="https://pixabay.com/api/",S="43457723-16bfd608d3311c06907a5c683";async function u(a,t=1){const o=new URLSearchParams({key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await b.get(`${w}?${o}`)).data}function h(a){return a.map(({webformatURL:t,largeImageURL:o,tags:i,likes:e,views:r,comments:n,downloads:g})=>`<li class="gallery-item">
        <div class="thumb">
            <a class="gallery-link" href="${o}">
              <img
                class="gallery-image"
                src="${t}"
                alt="${i}"
              />
            </a>
              <ul class="description-list">
                <li class="description-items"><span class="accent">Likes </span>${e}</li>
                <li class="description-items"><span class="accent">Views </span>${r}</li>
                <li class="description-items"><span class="accent">Comments </span>${n}</li>
                <li class="description-items"><span class="accent">Downloads </span>${g}</li>
              </ul>
        </div>
      </li>`).join("")}const c={title:"❌",titleSize:"24px",messageColor:"white",messageSize:"16px",backgroundColor:"rgba(225, 0, 0, 0.3)",position:"topRight",timeout:3e3};let d=1,p=null;const s={form:document.querySelector(".js-form"),list:document.querySelector(".js-list"),loader:document.querySelector(".js-loader"),btnLoadMore:document.querySelector(".btn-js-load-more")};s.btnLoadMore.addEventListener("click",v);s.form.addEventListener("submit",M);function f(){s.loader.style.display="block"}function m(){s.loader.style.display="none"}m();async function M(a){a.preventDefault();const t=s.form.elements.search.value.trim();if(t===""){l.show({...c,message:"Please enter a search term before submitting!"});return}p=t,d=1,f();try{const o=await u(t);if(o.hits.length===0){s.list.innerHTML="",l.show({...c,message:"Sorry, there are no images matching your search query. Please try again!"});return}s.list.innerHTML=h(o.hits),y.refresh(),s.btnLoadMore.classList.replace("btn-hidden-load-more","btn-load-more")}catch{s.list.innerHTML="",l.show({...c,message:"Sorry, there are no images matching your search query. Please try again!"})}finally{m()}}async function v(){f(),s.btnLoadMore.classList.replace("btn-load-more","btn-hidden-load-more");try{d+=1;const t=await u(p,d);s.list.insertAdjacentHTML("beforeend",h(t.hits)),y.refresh(),s.btnLoadMore.classList.replace("btn-hidden-load-more","btn-load-more");const{height:o}=s.list.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*3,behavior:"smooth"})}catch{l.show({...c,message:"We're sorry, but you've reached the end of search results."})}finally{m()}const a=Math.floor(data.totalHits/15);d===a&&s.btnLoadMore.classList.replace("btn-load-more","btn-hidden-load-more")}const y=new L(".js-list a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});
//# sourceMappingURL=commonHelpers.js.map
